name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy via flyctl
        run: flyctl deploy --remote-only
        working-directory: ./go-rest-api
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
